name: felicitup_app
description: 'A new Flutter project.'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Graphics
  cupertino_icons: ^1.0.8
  animate_do: ^3.3.8
  flutter_svg: ^2.0.17

  # State Management
  bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  flutter_bloc: ^9.0.0

  # Firebase
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.3.4
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_crashlytics: ^4.3.3
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4

  # Packages
  either_dart: ^1.0.0
  fast_contacts: ^4.0.0
  flutter_local_notifications: ^19.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.6.3
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  intl_utils: ^2.8.8
  json_annotation: ^4.9.0
  envied: ^1.1.0
  sign_in_with_apple: ^6.1.4

  # Utils
  image_picker: ^1.1.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  video_player: ^2.9.2

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500

flutter_intl:
  enabled: true
  class_name: IntlTrans
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/gen

flutter_gen:
  output: lib/gen

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon.png'
  min_sdk_android: 21
