# Uncomment this line to define a global platform for your project
platform :ios, '15.6'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # --- INICIO: Código añadido ---
      # Establece la versión mínima de despliegue para cada Pod.
      # Asegúrate de que esta versión coincida con la que pusiste en 'platform :ios, ...'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6' # O '14.0', etc.

      # Opcional: Silenciar otras advertencias comunes (puedes mantenerlas o quitarlas si no las necesitas)
      # config.build_settings['GCC_WARN_UNUSED_VARIABLE'] = 'NO'
      # config.build_settings['ENABLE_BITCODE'] = 'NO' # Bitcode está obsoleto
      # --- FIN: Código añadido ---

      # Mantén tu configuración de preprocesador existente
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        ## dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=1',
      ]
    end
  end
end
